version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - customnet
    volumes:
      - mongo:/db
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - customnet
    volumes:
      - redis:/redis
  backendwnode:
    image: backendnode
    container_name: backendnode
    ports:
      - "5000:5000"
    networks:
      - customnet
    volumes:
      - myvol:/app
      - MONGODB_local=mongo
      - REDIS_host=redis
    depends_on:
      - mongo
      - redis
networks:
  customnet:
    driver: bridge
volumes:
  mongo:
  redis:
  myvol:
