
name: Node.js CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Node js Version Name
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm start --if-present
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: goniusman/backend
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Docker Tag
      id: set_tag
      run: echo "::set-output name=tag::master-$(git rev-parse --short HEAD)"

    - name: Trigger Workflow in Repo B
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_B_PAT }}
        repository: goniusman/devops
        event-type: update-image-tag
        client-payload: '{"tag": "${{ steps.set_tag.outputs.tag }}"}'
    
    
    
    
    
    
    
    
    
